name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build da imagem Docker
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/meli-api:latest .

    - name: Push da imagem
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/meli-api:latest

    - name: Deploy na EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker stop meli-api || true
          sudo docker rm   meli-api || true
          docker system prune -a --volumes -f

          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/meli-api:latest
          sudo docker network create -d bridge meli-network || true


          sudo docker run -d \
            --name meli-api \
            --network meli-network \
            -p 8080:8080 \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/meli-api:latest

          sudo docker image prune -f
